version: "2.1"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./conf/grafana/dasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./conf/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - data:/var/lib/grafana/data
      - data:/var/lib/grafana/plugins
    depends_on:
      - prometheus-server
    networks:
      - net
    restart: always

  prometheus-server:
    image: prom/prometheus:v2.7.1
    ports:
      - '127.0.0.1:9090:9090'
    volumes:
      - data:/prometheus
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./conf/prometheus/rules:/etc/prometheus/rules
    depends_on:
      - prometheus-pushgateway
    networks:
      - net
    restart: always

  prometheus-pushgateway:
    image: prom/pushgateway:v0.6.0
    ports:
      - '127.0.0.1:9091:9091'
    networks:
      - net
    restart: always

volumes:
  data:

networks:
  net:
