global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:
- /etc/prometheus/rules
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus-server:9090
- job_name: prometheus-pushgateway
  honor_labels: true
  static_configs:
  - targets:
    - prometheus-pushgateway:9091

